const TEXT = {
  "sqli-login": {
    target: "A login form that checks a username and password against the lab_users table.",
    expected: "Only a correct username and password logs in. Any other input fails.",
    happened: "The server joined your text into the SQL string. A quote ended the string early, so your input became SQL logic and the password check could be skipped.",
    dev: "The query is built with an f-string. The database cannot tell your data apart from the query's own code.",
    fix: "Use parameterized queries so input is always data. Also hash passwords, limit login attempts and never show raw SQL errors to users.",
  },
  "sqli-search": {
    target: "A product search that filters the products table by name.",
    expected: "Only products whose name contains the search text appear.",
    happened: "The search text went straight into a LIKE pattern. Input that closes the string and adds a UNION SELECT makes the database put rows from another table into the same results.",
    dev: "The query is built with string formatting. UNION needs the same column count, which is why column count is probed first.",
    fix: "Use parameterized queries. Give the app a least-privilege database account that cannot read unrelated tables, and return generic error messages.",
  },
"xss-reflected": {
  target: "A search box whose results page echoes the search text back to the visitor.",
  expected: "The typed text is only ever displayed as text, never run as code.",
  happened: "Your input was inserted straight into the page's HTML. An <img> tag with a broken source and an onerror handler runs your JavaScript the moment the browser tries to load it.",
  dev: "The page builds HTML by concatenating the query string in, so any tag or attribute you type becomes real markup.",
  fix: "Encode user input before inserting it into HTML (React does this by default when you don't use dangerouslySetInnerHTML), and set a Content-Security-Policy header as a second layer of defense.",
},
"xss-stored": {
  target: "A comment board that saves visitor comments and displays them to everyone.",
  expected: "Comment text is shown as plain text, no matter what is typed.",
  happened: "The comment was saved exactly as typed and rendered as raw HTML for every visitor, including you on your next visit. The payload runs on every page load until it's removed.",
  dev: "The server stores the raw text and the page renders it as HTML instead of plain text.",
  fix: "Encode user content every time it is displayed (React does this for you when you render text normally, and only skips it with dangerouslySetInnerHTML). Never treat stored user content as trusted HTML.",
},
"auth-weak": {
  target: "A sign-up form that is supposed to enforce a password policy.",
  expected: "Weak passwords like \"1\" or \"password\" are rejected.",
  happened: "The signup endpoint accepted the password with no checks at all.",
  dev: "There is no server-side validation. Client-side-only checks are easy to bypass by calling the API directly.",
  fix: "Enforce a minimum length and character mix on the server, and check new passwords against a list of commonly breached passwords.",
},
"auth-rate": {
  target: "A login endpoint for a dummy account (bruteforce_target), reachable without being logged in, like a real login page.",
  expected: "After a handful of wrong attempts, further attempts should be slowed or blocked for that account.",
  happened: "Vulnerable mode allows unlimited attempts, so a wordlist attack (e.g. with Hydra) can try every password until one works.",
  dev: "The endpoint has no attempt counter or delay logic.",
  fix: "Lock or delay an account after repeated failures (as Secure mode does here), and add CAPTCHA or multi-factor authentication for extra protection.",
},
"xss-dom": {
  target: "A standalone page that greets you using a name taken from the URL after the # symbol.",
  expected: "Whatever is in the URL is shown as plain text, never run as code.",
  happened: "The page reads location.hash in the browser and writes it into the page with innerHTML. Because the # part of a URL is never sent to the server, this attack never touches your backend or its logs at all — the browser attacks itself.",
  dev: "innerHTML treats its input as HTML. Any tag typed after the # becomes real markup the moment the script runs.",
  fix: "Use textContent instead of innerHTML for untrusted data, or encode it first. Treat anything from location.hash, location.search or document.referrer as untrusted, exactly like server input.",
},
"authz-idor": {
  target: "A profile page that loads a user's profile by the ID in the URL.",
  expected: "You can only see your own profile. Other users' profiles should be refused.",
  happened: "The server returned any profile whose ID you asked for. It only checked that you were logged in, never that the profile was yours.",
  dev: "The endpoint trusts the ID from the URL as the object to return, with no ownership check (an Insecure Direct Object Reference).",
  fix: "On every request, check on the server that the logged-in user is allowed to access that specific object (as Secure mode does). Do not rely on IDs being hard to guess.",
},
"authz-admin": {
  target: "An admin endpoint that lists all users, plus a menu where the admin link is hidden from students.",
  expected: "Only admins can call the admin endpoint. A student should be refused even if they know the URL.",
  happened: "The developer only hid the link in the UI. The endpoint itself never checked the caller's role, so calling it directly worked.",
  dev: "Access control was implemented in the front end only. Anything the browser can hide, an attacker can still request.",
  fix: "Enforce the role check on the server for every protected endpoint, deny by default, and never rely on hidden menu items or client-side checks.",
},
"session-cookie": {
  target: "A session ID issuer, similar to what a login would set as a cookie.",
  expected: "Session IDs should be unpredictable, so one valid ID never reveals another.",
  happened: "IDs were handed out in a simple counting sequence. Seeing one ID lets you guess the next.",
  dev: "The ID generator uses itertools.count() instead of a cryptographically random source.",
  fix: "Generate session IDs with a secure random function (os.urandom or a framework's built-in session handling), long enough to not be guessable.",
},
"auth-storage": {
  target: "The table where user passwords are stored.",
  expected: "Even if the database leaks, passwords should not be directly readable.",
  happened: "Passwords were stored exactly as typed. Anyone with database access reads them instantly.",
  dev: "There is no hashing step between the signup form and the database write.",
  fix: "Hash passwords with a slow, salted algorithm (bcrypt, scrypt or Argon2), never store or log them in plain text.",
},
"file-traversal": {
  target: "An endpoint that reads a file by name from a public folder.",
  expected: "Only files inside that one public folder should ever be readable.",
  happened: "A filename containing ../ walked up out of the public folder and read a file that was never meant to be public.",
  dev: "The filename was joined directly into a file path with no validation.",
  fix: "Strip path components from user-supplied filenames (os.path.basename), and additionally verify the resolved path is still inside the allowed folder.",
},
"config-headers": {
  target: "Every response the server sends.",
  expected: "Responses should carry basic protective headers by default.",
  happened: "No security headers were set, leaving the app more open to clickjacking and MIME-sniffing attacks.",
  dev: "The server never added these headers to its responses.",
  fix: "Set X-Content-Type-Options, X-Frame-Options and a Content-Security-Policy on every response, ideally via shared middleware so no route can forget them.",
},
"logic-checkout": {
  target: "A checkout endpoint that charges for an item.",
  expected: "The price should always come from the server's own catalog, never from the request.",
  happened: "The endpoint used whatever price the client sent, and didn't check that quantity was positive, so 0.01 or a negative quantity changed the total.",
  dev: "Trusting client-supplied values for anything money-related is a business logic flaw, not a coding typo.",
  fix: "Always recalculate price and totals server-side from trusted data, and validate quantity bounds, regardless of what the client sends.",
},
"api-exposure": {
  target: "An API endpoint that lists users for the logged-in app.",
  expected: "The response should contain only the fields the client actually needs.",
  happened: "The response included password_hash and api_key for every user, fields no legitimate client screen needed.",
  dev: "The endpoint serialized the entire internal user object instead of a specific, minimal response shape.",
  fix: "Define an explicit response schema per endpoint and only include fields that are actually required.",
},
};
export const NAV = [
  { id: "dashboard", label: "Dashboard" }, { id: "labs", label: "Vulnerability Labs" },
  { id: "sqli", label: "SQL Injection", cat: "SQL Injection" }, { id: "xss", label: "XSS", cat: "XSS" },
  { id: "auth", label: "Authentication", cat: "Authentication" }, { id: "authz", label: "Authorization", cat: "Authorization" },
  { id: "api", label: "API Security", cat: "API Security" }, { id: "session", label: "Session Security", cat: "Session Security" },
  { id: "file", label: "File Security", cat: "File Security" }, { id: "config", label: "Configuration", cat: "Configuration" },
  { id: "logic", label: "Business Logic", cat: "Business Logic" }, { id: "reports", label: "Reports" },
  { id: "about", label: "About the Lab" },
];
// status "planned" = page exists, vulnerable endpoint not built yet.
export const LABS = [
  { id: "sqli-login", cat: "SQL Injection", title: "Login bypass", level: "Easy", area: "Login form", desc: "A lab login that builds its SQL query by joining strings." },
  { id: "sqli-search", cat: "SQL Injection", title: "Product search", level: "Medium", area: "Search box", desc: "A search that can be made to return rows from other tables." },
  { id: "xss-reflected", cat: "XSS", title: "Reflected XSS in search", level: "Easy", area: "Search results page", desc: "Input is echoed back into the page without encoding." },
  { id: "xss-stored", cat: "XSS", title: "Stored XSS in comments", level: "Medium", area: "Comment board", desc: "Saved comments are rendered as raw HTML for every visitor." },
  { id: "auth-weak", cat: "Authentication", title: "Weak password policy", level: "Easy", area: "Registration form", desc: "Sign-up accepts trivially guessable passwords." },
  { id: "auth-rate", cat: "Authentication", title: "No rate limiting", level: "Easy", area: "Login endpoint", desc: "Unlimited login attempts are allowed." },
  { id: "authz-idor", cat: "Authorization", title: "IDOR on profiles", level: "Easy", area: "Profile API", desc: "Changing the id in the request returns another user's record." },
  { id: "authz-admin", cat: "Authorization", title: "Broken access control", level: "Medium", area: "Admin panel", desc: "The admin link is hidden but the server never checks the role." },
  { id: "session-cookie", cat: "Session Security", title: "Predictable session ID", level: "Medium", area: "Session cookie", desc: "Session IDs are sequential and can be guessed." },
  { id: "auth-storage", cat: "Authentication", title: "Weak password storage", level: "Easy", area: "User database", desc: "Passwords are stored in plain text instead of hashed." },
  { id: "file-traversal", cat: "File Security", title: "Path traversal", level: "Medium", area: "File download endpoint", desc: "A file-name parameter can be made to read files outside the intended folder." },
  { id: "config-headers", cat: "Configuration", title: "Missing security headers", level: "Easy", area: "HTTP responses", desc: "Responses lack basic protective headers like X-Frame-Options and CSP." },
  { id: "logic-checkout", cat: "Business Logic", title: "Price manipulation", level: "Medium", area: "Checkout endpoint", desc: "The client sends the price, and the server trusts it instead of recalculating." },
  { id: "api-exposure", cat: "API Security", title: "Excessive data exposure", level: "Medium", area: "Users API", desc: "An API response includes sensitive fields the app never needed to send." },
  { id: "xss-dom", cat: "XSS", title: "DOM-based XSS in a greeting page", level: "Medium", area: "Standalone HTML page (client-side only)", desc: "A page reads the URL and writes it straight into the DOM with no server round trip.", noServer: true },
].map(l => ({ ...l, status: TEXT[l.id] ? "ready" : "planned" }));

export { TEXT };
